{{- include "cc-rc.validateGithubAuth" . -}}
{{- if .Values.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.github.secretName }}
  labels:
    {{- include "cc-rc.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.github.secretKey }}: {{ .Values.github.token | quote }}
{{- end }}
